version: '3.8'
services:
  redis-server:
    container_name: url-shortener-redis
    image: redis:alpine 
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
  
volumes:
  redis-data: